pub mod analytics;
pub mod eden;
pub mod endpoint;
pub mod iam;
pub mod metadata;
pub mod proxy;
pub mod snapshot;
pub mod validator;
pub mod workload;

use crate::guards::EndpointGuard;
use crate::labels::{LABEL_TRAFFIC_CLASS, TelemetryLabels};
use crate::metrics::analytics::AnalyticsMetrics;
use crate::metrics::eden::EdenMetrics;
use crate::metrics::endpoint::EndpointMetrics;
use crate::metrics::iam::IamMetrics;
use crate::metrics::metadata::MetadataMetrics;
use crate::metrics::proxy::ProxyMetrics;
use crate::metrics::snapshot::SnapshotMetrics;
use crate::metrics::validator::ValidatorMetrics;
use crate::metrics::workload::WorkloadMetrics;
use crate::{MetadataMapWrapper, TelemetryDurations, TelemetryWrapper, TraceContext};
use actix_web::body::BodySize;
use actix_web::http::StatusCode;
use actix_web::web::Data;
use actix_web::{HttpMessage, HttpResponse, dev::ServiceResponse, web};
use auth::ParsedJwt;
use chrono::{DateTime, Utc};
use eden_logger_internal::{ctx_with_trace, log_trace};
use fast_telemetry::DynamicLabelSet;
use fast_telemetry::advance_cycle;
#[cfg(feature = "clickhouse")]
use fast_telemetry::clickhouse::ClickHouseMetricBatch;
use fast_telemetry::span::SpanCollector;
use format::EdenNodeUuid;
use format::id::Username;
use function_name::named;
use request::{DEFAULT_VERBOSE, HEADER_VERBOSE, ServerData};
use serde::Serialize;
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;
use std::string::ToString;
use std::sync::Arc;
use tokio::sync::RwLock;

// Re-export delta state types generated by ExportMetrics derive macro
pub use crate::metrics::analytics::AnalyticsMetricsDogStatsDState;
pub use crate::metrics::eden::EdenCoreMetricsDogStatsDState;
pub use crate::metrics::endpoint::EndpointMetricsDogStatsDState;
pub use crate::metrics::iam::IamMetricsDogStatsDState;
pub use crate::metrics::metadata::MetadataMetricsDogStatsDState;
pub use crate::metrics::proxy::ProxyMetricsDogStatsDState;
pub use crate::metrics::proxy::{
    ProxyBatchRecord, ProxyBridgeSeries, ProxyLanePoolSeries, ProxyMirrorSeries, ProxyMultiplexSeries, ProxySeries,
};
pub use crate::metrics::snapshot::SnapshotMetricsDogStatsDState;
pub use crate::metrics::validator::ValidatorMetricsDogStatsDState;
pub use crate::metrics::workload::WorkloadMetricsDogStatsDState;

/// Default eviction threshold: series inactive for this many export cycles are evicted.
const DEFAULT_EVICTION_THRESHOLD: u32 = 6;

/// State for delta temporality exports (required for Datadog).
///
/// Tracks previous values to compute deltas between export intervals.
/// Eviction is now handled internally by each dynamic metric type using
/// access-timestamp tracking.
pub struct FastMetricsExportState {
    pub eden: EdenCoreMetricsDogStatsDState,
    pub iam: IamMetricsDogStatsDState,
    pub endpoint: EndpointMetricsDogStatsDState,
    pub analytics: AnalyticsMetricsDogStatsDState,
    pub metadata: MetadataMetricsDogStatsDState,
    pub proxy: ProxyMetricsDogStatsDState,
    pub snapshot: SnapshotMetricsDogStatsDState,
    pub workload: WorkloadMetricsDogStatsDState,
    pub validator: ValidatorMetricsDogStatsDState,
    /// Eviction threshold: series inactive for this many cycles are evicted.
    pub eviction_threshold: u32,
    /// Previous cumulative value for span sampling delta export.
    prev_spans_recorded: u64,
    prev_spans_sampled_out: u64,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DynamicSeriesCardinalitySnapshot {
    pub eden: usize,
    pub iam: usize,
    pub endpoint: usize,
    pub analytics: usize,
    pub metadata: usize,
    pub proxy: usize,
    pub snapshot: usize,
    pub workload: usize,
    pub validator: usize,
}

impl DynamicSeriesCardinalitySnapshot {
    pub fn total(&self) -> usize {
        self.eden + self.iam + self.endpoint + self.analytics + self.metadata + self.proxy + self.snapshot + self.workload + self.validator
    }
}

impl FastMetricsExportState {
    pub fn new() -> Self {
        Self::with_eviction_threshold(DEFAULT_EVICTION_THRESHOLD)
    }

    /// Create export state with custom eviction threshold.
    ///
    /// `threshold` is the number of consecutive export cycles a series must be
    /// inactive before being evicted.
    pub fn with_eviction_threshold(threshold: u32) -> Self {
        Self {
            eden: EdenCoreMetricsDogStatsDState::new(),
            iam: IamMetricsDogStatsDState::new(),
            endpoint: EndpointMetricsDogStatsDState::new(),
            analytics: AnalyticsMetricsDogStatsDState::new(),
            metadata: MetadataMetricsDogStatsDState::new(),
            proxy: ProxyMetricsDogStatsDState::new(),
            snapshot: SnapshotMetricsDogStatsDState::new(),
            workload: WorkloadMetricsDogStatsDState::new(),
            validator: ValidatorMetricsDogStatsDState::new(),
            eviction_threshold: threshold,
            prev_spans_recorded: 0,
            prev_spans_sampled_out: 0,
        }
    }
    /// Total number of dynamic label sets retained in delta-export state maps.
    pub fn tracked_label_sets(&self) -> usize {
        self.eden.tracked_label_sets()
            + self.iam.tracked_label_sets()
            + self.endpoint.tracked_label_sets()
            + self.analytics.tracked_label_sets()
            + self.metadata.tracked_label_sets()
            + self.proxy.tracked_label_sets()
            + self.snapshot.tracked_label_sets()
            + self.workload.tracked_label_sets()
            + self.validator.tracked_label_sets()
    }
}

impl Default for FastMetricsExportState {
    fn default() -> Self {
        Self::new()
    }
}

pub struct AllMetrics {
    analytics: AnalyticsMetrics,
    eden: EdenMetrics,
    iam: IamMetrics,
    endpoint: EndpointMetrics,
    metadata: MetadataMetrics,
    proxy: ProxyMetrics,
    snapshot: SnapshotMetrics,
    workload: WorkloadMetrics,
    validator: ValidatorMetrics,
    /// Thread-sharded span collector for fast-telemetry distributed tracing.
    span_collector: Arc<SpanCollector>,
}

#[cfg(feature = "clickhouse")]
pub struct ClickHouseMetricGroupBatch {
    pub analytics: ClickHouseMetricBatch,
    pub eden: ClickHouseMetricBatch,
    pub iam: ClickHouseMetricBatch,
    pub endpoint: ClickHouseMetricBatch,
    pub metadata: ClickHouseMetricBatch,
    pub proxy: ClickHouseMetricBatch,
    pub snapshot: ClickHouseMetricBatch,
    pub workload: ClickHouseMetricBatch,
    pub validator: ClickHouseMetricBatch,
}

#[cfg(feature = "clickhouse")]
impl ClickHouseMetricGroupBatch {
    pub fn new(service_name: impl Into<String>, node_uuid: impl Into<String>) -> Self {
        let service_name = service_name.into();
        let node_uuid = node_uuid.into();
        Self {
            analytics: Self::batch(&service_name, &node_uuid, "analytics"),
            eden: Self::batch(&service_name, &node_uuid, "eden"),
            iam: Self::batch(&service_name, &node_uuid, "eden.iam"),
            endpoint: Self::batch(&service_name, &node_uuid, "eden.endpoint"),
            metadata: Self::batch(&service_name, &node_uuid, "redis"),
            proxy: Self::batch(&service_name, &node_uuid, "proxy"),
            snapshot: Self::batch(&service_name, &node_uuid, "snapshot"),
            workload: Self::batch(&service_name, &node_uuid, "workload"),
            validator: Self::batch(&service_name, &node_uuid, "eden.validator"),
        }
    }

    fn batch(service_name: &str, node_uuid: &str, scope_name: &str) -> ClickHouseMetricBatch {
        ClickHouseMetricBatch::with_scope(service_name, scope_name).with_resource_attribute("eden.node_uuid", node_uuid)
    }

    pub fn clear(&mut self) {
        self.analytics.clear();
        self.eden.clear();
        self.iam.clear();
        self.endpoint.clear();
        self.metadata.clear();
        self.proxy.clear();
        self.snapshot.clear();
        self.workload.clear();
        self.validator.clear();
    }
}

impl Default for AllMetrics {
    fn default() -> Self {
        Self::new()
    }
}

impl AllMetrics {
    /// Create a new AllMetrics instance with all fast-telemetry metrics initialized.
    ///
    /// The span collector uses `num_cpus` shards with 8192 capacity per shard,
    /// providing high-throughput span collection with minimal contention.
    pub fn new() -> Self {
        // Use number of CPUs for sharding to minimize cross-thread contention.
        // 8192 capacity per shard is sufficient for typical request bursts.
        let num_shards = std::thread::available_parallelism().map(|p| p.get()).unwrap_or(8);
        let span_collector = Arc::new(SpanCollector::new(num_shards, 8192));

        Self {
            eden: EdenMetrics::new(),
            iam: IamMetrics::new(),
            endpoint: EndpointMetrics::new(),
            analytics: AnalyticsMetrics::new(),
            metadata: MetadataMetrics::new(),
            proxy: ProxyMetrics::new(),
            snapshot: SnapshotMetrics::new(),
            workload: WorkloadMetrics::new(),
            validator: ValidatorMetrics::new(),
            span_collector,
        }
    }

    pub fn analytics(&self) -> &AnalyticsMetrics {
        &self.analytics
    }
    pub fn mut_analytics(&mut self) -> &mut AnalyticsMetrics {
        &mut self.analytics
    }
    pub fn eden(&self) -> &EdenMetrics {
        &self.eden
    }
    pub fn mut_eden(&mut self) -> &mut EdenMetrics {
        &mut self.eden
    }
    pub fn iam(&self) -> &IamMetrics {
        &self.iam
    }
    pub fn mut_iam(&mut self) -> &mut IamMetrics {
        &mut self.iam
    }
    pub fn endpoint(&self) -> &EndpointMetrics {
        &self.endpoint
    }
    pub fn mut_endpoint(&mut self) -> &mut EndpointMetrics {
        &mut self.endpoint
    }
    pub fn metadata(&self) -> &MetadataMetrics {
        &self.metadata
    }
    pub fn mut_metadata(&mut self) -> &mut MetadataMetrics {
        &mut self.metadata
    }
    pub fn proxy(&self) -> &ProxyMetrics {
        &self.proxy
    }
    pub fn mut_proxy(&mut self) -> &mut ProxyMetrics {
        &mut self.proxy
    }
    pub fn snapshot(&self) -> &SnapshotMetrics {
        &self.snapshot
    }
    pub fn mut_snapshot(&mut self) -> &mut SnapshotMetrics {
        &mut self.snapshot
    }
    pub fn workload(&self) -> &WorkloadMetrics {
        &self.workload
    }
    pub fn mut_workload(&mut self) -> &mut WorkloadMetrics {
        &mut self.workload
    }
    pub fn validator(&self) -> &ValidatorMetrics {
        &self.validator
    }
    pub fn mut_validator(&mut self) -> &mut ValidatorMetrics {
        &mut self.validator
    }

    /// Get the span collector for distributed tracing.
    ///
    /// Use this to create spans via `span_collector.start_span()` or
    /// `span_collector.start_span_from_traceparent()`.
    pub fn span_collector(&self) -> &Arc<SpanCollector> {
        &self.span_collector
    }

    /// Export fast-telemetry metrics in DogStatsD format with delta temporality.
    ///
    /// Required for Datadog which expects delta values (counts since last export).
    pub fn export_dogstatsd_delta(&self, output: &mut String, tags: &[(&str, &str)], state: &mut FastMetricsExportState) {
        self.eden.core.export_dogstatsd_delta(output, tags, &mut state.eden);
        self.iam.export_dogstatsd_delta(output, tags, &mut state.iam);
        self.endpoint.export_dogstatsd_delta(output, tags, &mut state.endpoint);
        self.analytics.export_dogstatsd_delta(output, tags, &mut state.analytics);
        self.metadata.export_dogstatsd_delta(output, tags, &mut state.metadata);
        self.proxy.export_dogstatsd_delta(output, tags, &mut state.proxy);
        self.snapshot.export_dogstatsd_delta(output, tags, &mut state.snapshot);
        self.workload.export_dogstatsd_delta(output, tags, &mut state.workload);
        self.validator.export_dogstatsd_delta(output, tags, &mut state.validator);

        // Span sampling counters — manual delta export.
        let recorded = self.span_collector.recorded_count();
        let sampled_out = self.span_collector.sampled_out_count();
        let delta_recorded = recorded.wrapping_sub(state.prev_spans_recorded);
        let delta_sampled_out = sampled_out.wrapping_sub(state.prev_spans_sampled_out);
        state.prev_spans_recorded = recorded;
        state.prev_spans_sampled_out = sampled_out;

        if delta_recorded > 0 || delta_sampled_out > 0 {
            use std::fmt::Write;
            let tag_str: String = tags.iter().map(|(k, v)| format!("{k}:{v}")).collect::<Vec<_>>().join(",");
            let _ = writeln!(output, "span.sampling.recorded:{delta_recorded}|c|#{tag_str}");
            let _ = writeln!(output, "span.sampling.sampled_out:{delta_sampled_out}|c|#{tag_str}");
        }
    }

    /// Sweep stale dynamic metric series and evict them.
    ///
    /// Call this after each export cycle to bound memory usage from dynamic labels.
    /// Returns the total number of series evicted.
    pub fn sweep_stale_series(&self, state: &FastMetricsExportState) -> usize {
        // Advance the global eviction cycle
        advance_cycle();

        let threshold = state.eviction_threshold;
        let mut total_evicted = 0;

        // Evict stale series from all metric types
        total_evicted += self.proxy.evict_stale(threshold);
        total_evicted += self.eden.evict_stale(threshold);
        total_evicted += self.endpoint.evict_stale(threshold);
        total_evicted += self.workload.evict_stale(threshold);
        total_evicted += self.snapshot.evict_stale(threshold);
        total_evicted += self.iam.evict_stale(threshold);
        total_evicted += self.metadata.evict_stale(threshold);
        total_evicted += self.validator.evict_stale(threshold);

        total_evicted
    }

    /// Evict stale dynamic metric series using an explicit inactivity threshold.
    ///
    /// Kept for compatibility with callers that do not use `FastMetricsExportState`.
    pub fn evict_stale_series(&self, threshold: u32) -> usize {
        advance_cycle();

        let mut total_evicted = 0;
        total_evicted += self.proxy.evict_stale(threshold);
        total_evicted += self.eden.evict_stale(threshold);
        total_evicted += self.endpoint.evict_stale(threshold);
        total_evicted += self.workload.evict_stale(threshold);
        total_evicted += self.snapshot.evict_stale(threshold);
        total_evicted += self.iam.evict_stale(threshold);
        total_evicted += self.metadata.evict_stale(threshold);
        total_evicted += self.validator.evict_stale(threshold);
        total_evicted
    }

    /// Export all fast-telemetry metrics as OTLP protobuf `Metric` messages.
    ///
    /// Uses cumulative temporality and computes a single timestamp for all data points.
    #[cfg(feature = "otlp")]
    pub fn export_otlp(&self, metrics: &mut Vec<fast_telemetry::otlp::pb::Metric>) {
        let time_unix_nano = fast_telemetry::otlp::now_nanos();
        self.eden.core.export_otlp(metrics, time_unix_nano);
        self.iam.export_otlp(metrics, time_unix_nano);
        self.endpoint.export_otlp(metrics, time_unix_nano);
        self.analytics.export_otlp(metrics, time_unix_nano);
        self.metadata.export_otlp(metrics, time_unix_nano);
        self.proxy.export_otlp(metrics, time_unix_nano);
        self.snapshot.export_otlp(metrics, time_unix_nano);
        self.workload.export_otlp(metrics, time_unix_nano);
        self.validator.export_otlp(metrics, time_unix_nano);
    }

    /// Export all fast-telemetry metrics into Eden ClickHouse metric groups.
    #[cfg(feature = "clickhouse")]
    pub fn export_clickhouse(&self, batches: &mut ClickHouseMetricGroupBatch, time_unix_nano: u64) {
        batches.clear();
        self.eden.core.export_clickhouse(&mut batches.eden, time_unix_nano);
        self.iam.export_clickhouse(&mut batches.iam, time_unix_nano);
        self.endpoint.export_clickhouse(&mut batches.endpoint, time_unix_nano);
        self.analytics.export_clickhouse(&mut batches.analytics, time_unix_nano);
        self.metadata.export_clickhouse(&mut batches.metadata, time_unix_nano);
        self.proxy.export_clickhouse(&mut batches.proxy, time_unix_nano);
        self.snapshot.export_clickhouse(&mut batches.snapshot, time_unix_nano);
        self.workload.export_clickhouse(&mut batches.workload, time_unix_nano);
        self.validator.export_clickhouse(&mut batches.validator, time_unix_nano);
    }

    /// Export only high-frequency live metrics into Eden ClickHouse metric groups.
    #[cfg(feature = "clickhouse")]
    pub fn export_clickhouse_live(&self, batches: &mut ClickHouseMetricGroupBatch, _time_unix_nano: u64) {
        batches.clear();
    }

    /// Get total cardinality of dynamic proxy metrics.
    pub fn proxy_cardinality(&self) -> usize {
        self.proxy.cardinality()
    }

    /// Snapshot dynamic series cardinality across all metric families.
    pub fn dynamic_series_cardinality_snapshot(&self) -> DynamicSeriesCardinalitySnapshot {
        DynamicSeriesCardinalitySnapshot {
            eden: self.eden.cardinality(),
            iam: self.iam.cardinality(),
            endpoint: self.endpoint.cardinality(),
            analytics: self.analytics.cardinality(),
            metadata: self.metadata.cardinality(),
            proxy: self.proxy.series_cardinality(),
            snapshot: self.snapshot.cardinality(),
            workload: self.workload.cardinality(),
            validator: self.validator.cardinality(),
        }
    }

    /// Snapshot cumulative LLM total tokens grouped by dynamic labels.
    pub fn snapshot_llm_total_tokens(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.eden.snapshot_llm_total_tokens()
    }

    /// Snapshot cumulative LLM prompt tokens grouped by dynamic labels.
    pub fn snapshot_llm_prompt_tokens(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.eden.snapshot_llm_prompt_tokens()
    }

    /// Snapshot cumulative LLM completion tokens grouped by dynamic labels.
    pub fn snapshot_llm_completion_tokens(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.eden.snapshot_llm_completion_tokens()
    }

    /// Snapshot cumulative endpoint request counts grouped by dynamic labels.
    pub fn snapshot_endpoint_total_requests(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.endpoint.snapshot_total_requests()
    }

    /// Snapshot cumulative uploaded request bytes grouped by dynamic labels.
    pub fn snapshot_upload_bytes(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.eden.snapshot_upload_bytes()
    }

    /// Snapshot cumulative downloaded response bytes grouped by dynamic labels.
    pub fn snapshot_download_bytes(&self) -> Vec<(DynamicLabelSet, isize)> {
        self.eden.snapshot_download_bytes()
    }

    /// Snapshot current endpoint connections grouped by db_type / endpoint_uuid labels.
    pub fn snapshot_connections(&self) -> Vec<(DynamicLabelSet, i64)> {
        self.eden.snapshot_connections()
    }

    /// Snapshot current endpoint connections in use (checked out of the pool).
    pub fn snapshot_connections_in_use(&self) -> Vec<(DynamicLabelSet, i64)> {
        self.eden.snapshot_connections_in_use()
    }

    /// Snapshot current active proxy connections grouped by interlay/endpoint labels.
    pub fn snapshot_proxy_connections(&self) -> Vec<(DynamicLabelSet, i64)> {
        self.proxy.snapshot_active_connections()
    }
}

/// Creates AllMetrics for fast-telemetry metrics collection.
///
/// Arguments are kept for backward compatibility but are no longer used.
/// Exporters consume this local metrics registry only when their feature or
/// runtime configuration enables them.
#[allow(unused_variables)]
pub fn setup_metrics(_collector_endpoint: &str, _db_collector_endpoint: &str) -> Result<AllMetrics, Box<dyn std::error::Error>> {
    Ok(AllMetrics::new())
}

/// Middleware struct that will be used to wrap the service
#[derive(Clone, Default)]
pub struct MetricsMiddleware {}

pub struct MetricsMiddlewareService<S> {
    service: S,
}
impl<S, B> MetricsMiddlewareService<S>
where
    S: actix_web::dev::Service<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<B>, Error = actix_web::Error>,
    S::Future: 'static,
    B: 'static,
{
    fn start_request(
        &self,
        req: &actix_web::dev::ServiceRequest,
        metrics: Data<AllMetrics>,
    ) -> (DateTime<Utc>, TelemetryWrapper, Username, u64) {
        let start = Utc::now();
        let eden_node_uuid = if let Some(server_data) = req.app_data::<Data<ServerData>>() {
            server_data.public_key.clone()
        } else {
            EdenNodeUuid::new_uuid()
        };
        let metadata = req.extensions().get::<MetadataMapWrapper>().cloned().unwrap_or_else(|| {
            // Extract trace context from HTTP headers (traceparent, tracestate, etc.)
            use crate::metadata_map_from_http_headers;
            metadata_map_from_http_headers(req.headers()).into()
        });

        // Store metadata in request extensions for handlers to access via #[with_telemetry] macro
        req.extensions_mut().insert(metadata.clone());

        let mut labels = req.extensions().get::<TelemetryLabels>().cloned().unwrap_or_else(|| TelemetryLabels::new(&eden_node_uuid));

        // Populate HTTP headers from metadata for metrics labels
        labels.populate_from_metadata(metadata.metadata());
        let durations = req.extensions().get::<TelemetryDurations>().cloned().unwrap_or_default();

        let mut telemetry_wrapper = TelemetryWrapper::new_with_telemetry(
            TraceContext::from(metadata.metadata().clone()),
            metrics.clone().into_inner(),
            labels,
            durations,
        );

        // Set eden request start time
        telemetry_wrapper.set_eden_request_start(start);

        telemetry_wrapper.mut_labels(|labels| {
            labels.set_http_path(req.path());
            labels.set_http_method(req.method());
        });

        // Add user and org context if available
        let user;
        if let Some(auth) = req.extensions().get::<web::ReqData<ParsedJwt>>() {
            telemetry_wrapper.mut_labels(|labels| {
                labels.set_jwt(auth.clone().into_inner());
            });
            user = Username::new(auth.org_uuid().clone(), auth.user_id().clone());
        } else {
            user = Username::default()
        }

        // Track request size
        let request_length =
            req.headers().get("content-length").and_then(|h| h.to_str().ok()).and_then(|v| v.parse::<u64>().ok()).unwrap_or(0);

        (start, telemetry_wrapper, user, request_length)
    }
}

// Define a struct to hold your metadata
#[derive(Debug, Clone, Serialize)]
pub struct RequestMetadata {
    pub user_id: Username,
    pub request_id: String,
    pub request_start: DateTime<Utc>,
    pub client_info: Option<String>,
    pub request_size: u64,
    pub endpoint: String,
    pub method: String,
}

fn insert_traceparent_header(response_builder: &mut actix_web::HttpResponseBuilder, traceparent: &str) {
    if !traceparent.is_empty() {
        response_builder.insert_header(("traceparent", traceparent.to_string()));
    }
}

fn body_size_or_content_length<B: actix_web::body::MessageBody>(body: &B, headers: &actix_web::http::header::HeaderMap) -> u64 {
    if let BodySize::Sized(size) = body.size() {
        return size;
    }
    headers.get("content-length").and_then(|h| h.to_str().ok()).and_then(|v| v.parse::<u64>().ok()).unwrap_or(0)
}

// Add this to your Transform trait implementation
impl<S, B> actix_web::dev::Transform<S, actix_web::dev::ServiceRequest> for MetricsMiddleware
where
    S: actix_web::dev::Service<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<B>, Error = actix_web::Error>
        + 'static,
    S::Future: 'static,
    B: actix_web::body::MessageBody + 'static,
    B::Error: actix_web::ResponseError, // Add this constraint
{
    type Response = actix_web::dev::ServiceResponse<actix_web::body::EitherBody<B>>; // Change this
    type Error = actix_web::Error;
    type Transform = MetricsMiddlewareService<S>;
    type InitError = ();
    type Future = std::future::Ready<Result<Self::Transform, Self::InitError>>;

    fn new_transform(&self, service: S) -> Self::Future {
        std::future::ready(Ok(MetricsMiddlewareService {
            service,
            // metrics: self.metrics.clone(),
        }))
    }
}

impl<S, B> actix_web::dev::Service<actix_web::dev::ServiceRequest> for MetricsMiddlewareService<S>
where
    S: actix_web::dev::Service<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<B>, Error = actix_web::Error>
        + 'static,
    S::Future: 'static,
    B: actix_web::body::MessageBody + 'static,
    B::Error: actix_web::ResponseError, // Add this constraint
{
    type Response = actix_web::dev::ServiceResponse<actix_web::body::EitherBody<B>>; // Change this
    type Error = actix_web::Error;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&self, ctx: &mut core::task::Context<'_>) -> std::task::Poll<Result<(), Self::Error>> {
        self.service.poll_ready(ctx)
    }
    #[named]
    fn call(&self, req: actix_web::dev::ServiceRequest) -> Self::Future {
        // Clone what we need for the async block
        let metrics_clone = match req.app_data::<Data<AllMetrics>>() {
            Some(metrics) => metrics.clone(),
            None => {
                let fut = self.service.call(req);
                return Box::pin(async move { fut.await.map(|res| res.map_into_left_body()) });
            }
        };

        let (start, mut telemetry_wrapper, user, request_length) = self.start_request(&req, metrics_clone.clone());

        // Record eden request start time for duration tracking
        telemetry_wrapper.mut_durations(|durations| durations.set_eden_request(start));

        let mut span = telemetry_wrapper.server_tracer("eden.http.request".to_string());
        span.set_attribute("component", "http");
        span.set_attribute("http.method", req.method().as_str().to_string());
        span.set_attribute("http.route", req.path().to_string());
        span.set_attribute(LABEL_TRAFFIC_CLASS, telemetry_wrapper.labels().traffic_class().to_string());
        let trace_id = span.trace_id().to_string();
        let span_id = span.span_id().to_string();
        let response_traceparent = span.traceparent();
        span.enter(); // Set as current span for logging

        // Check if client wants verbose response
        let wants_verbose = req.query_string().contains("verbose=true")
            || req.headers().get(HEADER_VERBOSE).and_then(|h| h.to_str().ok()).map(|v| v == "true").unwrap_or(DEFAULT_VERBOSE);

        // Create metadata for verbose mode
        let metadata = if wants_verbose {
            Some(RequestMetadata {
                user_id: user.clone(),
                request_id: uuid::Uuid::new_v4().to_string(),
                request_start: start,
                client_info: req.headers().get("user-agent").and_then(|h| h.to_str().ok()).map(|s| s.to_string()),
                request_size: request_length,
                endpoint: req.path().to_string(),
                method: req.method().to_string(),
            })
        } else {
            None
        };

        // Store metadata in request extensions if verbose
        if let Some(ref meta) = metadata {
            req.extensions_mut().insert(meta.clone());
        }

        let mut extensions = req.extensions_mut();
        extensions.insert(telemetry_wrapper.labels().clone());
        extensions.insert(telemetry_wrapper.durations().clone());
        extensions.insert(telemetry_wrapper.metadata_map().clone());
        let telemetry_data = web::Data::new(RwLock::new(telemetry_wrapper));
        extensions.insert(telemetry_data.clone());
        // Store trace IDs for downstream use
        extensions.insert((trace_id.clone(), span_id.clone()));

        drop(extensions);
        let _ctx = ctx_with_trace!().with_feature("telemetry");

        let service_fut = self.service.call(req);
        Box::pin(async move {
            // Keep the request span alive until the wrapped service completes.
            let _request_span = span;

            // Extract trace IDs and update labels BEFORE cloning
            let labels_clone = {
                let mut tw = telemetry_data.write().await;

                // Update labels with trace IDs captured at span creation
                tw.mut_labels(|labels| {
                    labels.set_trace_ids(trace_id, span_id);
                });

                let labels = tw.labels_low_cardinality();
                log_trace!(
                    _ctx.clone(),
                    "Metrics -- client tracer initialized",
                    audience = eden_logger_internal::LogAudience::Internal
                );

                labels
            };

            // Helper to convert owned labels to refs
            fn labels_to_refs(labels: &[(String, String)]) -> Vec<(&str, &str)> {
                labels.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect()
            }

            let labels_refs = labels_to_refs(&labels_clone);
            metrics_clone.eden.start_request(user.clone(), request_length, &labels_refs).await;
            log_trace!(
                _ctx.clone(),
                "Metrics -- request started with labels",
                audience = eden_logger_internal::LogAudience::Internal,
                labels = format!("{:?}", labels_clone)
            );
            let endpoint_start = Utc::now();
            let _endpoint_guard = EndpointGuard::new(&metrics_clone.endpoint, &labels_refs);
            drop(labels_refs);
            let active_labels_clone = labels_clone;

            // Handle the future result
            match service_fut.await {
                Ok(service_response) => {
                    let endpoint_end = Utc::now();
                    let end = endpoint_end;

                    let (request, http_response) = service_response.into_parts();

                    let status = http_response.status();
                    let headers = http_response.headers().clone();

                    let (mut http_response, body) = http_response.into_parts();

                    let labels_clone = {
                        let (opt_labels, opt_durations) = {
                            let extensions_mut = http_response.extensions_mut();
                            (
                                extensions_mut.get::<TelemetryLabels>().cloned(),
                                extensions_mut.get::<TelemetryDurations>().cloned(),
                            )
                        };

                        if opt_labels.is_some() || opt_durations.is_some() {
                            let mut tw = telemetry_data.write().await;
                            if let Some(labels) = opt_labels {
                                log_trace!(
                                    _ctx.clone(),
                                    "Metrics -- service responded with labels",
                                    audience = eden_logger_internal::LogAudience::Internal,
                                    labels = format!("{:?}", labels)
                                );
                                tw.labels = labels;
                            }
                            if let Some(handler_durations) = opt_durations {
                                log_trace!(
                                    _ctx.clone(),
                                    "Metrics -- service responded with durations",
                                    audience = eden_logger_internal::LogAudience::Internal,
                                    durations = format!("{:?}", handler_durations)
                                );

                                // Merge durations intelligently: preserve eden_request/eden_response from middleware,
                                // but allow handlers to set endpoint_request/endpoint_response
                                tw.durations.merge_from_handler(handler_durations);
                            }

                            // If handler didn't set endpoint duration, set it explicitly from middleware timing
                            if tw.durations.get_endpoint_duration().is_none() {
                                tw.durations.set_endpoint_request(endpoint_start);
                                tw.durations.set_endpoint_response(endpoint_end);
                            }

                            tw.labels_low_cardinality()
                        } else {
                            // No handler updates, but still set endpoint duration if not set
                            let mut tw = telemetry_data.write().await;
                            if tw.durations.get_endpoint_duration().is_none() {
                                tw.durations.set_endpoint_request(endpoint_start);
                                tw.durations.set_endpoint_response(endpoint_end);
                            }
                            tw.labels_low_cardinality()
                        }
                    };
                    // finish endpoint request

                    // Skip verbose mode for streaming responses (SSE, etc.)
                    let is_streaming_response = headers
                        .get("content-type")
                        .and_then(|h| h.to_str().ok())
                        .map(|ct| ct.contains("text/event-stream") || ct.contains("text/plain"))
                        .unwrap_or(false);

                    if wants_verbose && !is_streaming_response {
                        let durations = {
                            let mut tw = telemetry_data.write().await;
                            tw.set_eden_request_end(end);
                            tw.mut_labels(|labels| {
                                labels.set_http_status(status);
                                // Note: trace IDs already set in async_block initialization
                            });
                            tw.durations.clone()
                        };

                        let metadata = match metadata {
                            Some(m) => m,
                            None => {
                                let mut response_builder = HttpResponse::build(status);
                                for (name, value) in headers.iter() {
                                    response_builder.insert_header((name.clone(), value.clone()));
                                }
                                insert_traceparent_header(&mut response_builder, &response_traceparent);
                                let http_response = response_builder.body(body);
                                let service_response = ServiceResponse::new(request, http_response).map_into_right_body();
                                return Ok(service_response);
                            }
                        };

                        let size = if let BodySize::Sized(size) = body.size() { size } else { 0 };

                        // Use pre-calculated durations from telemetry_data (optimized approach)
                        let eden_duration = durations.eden_duration.unwrap_or_default().as_duration();
                        let endpoint_duration = durations.endpoint_duration.unwrap_or_default().as_duration();
                        let exclusive_duration = durations.exclusive_duration.unwrap_or_default().as_duration();

                        // Calculate for JSON metadata compatibility
                        let total_duration_ms = eden_duration.num_milliseconds();
                        let total_duration_us = eden_duration.num_microseconds().unwrap_or(0);
                        let endpoint_processing_time_ms = endpoint_duration.num_milliseconds();
                        let endpoint_processing_time_us = endpoint_duration.num_microseconds().unwrap_or(0);
                        let exclusive_duration_ms = exclusive_duration.num_milliseconds();
                        let exclusive_duration_us = exclusive_duration.num_microseconds().unwrap_or(0);

                        // Get user info
                        let (org_uuid, user_id_val) = user.parts();
                        let (org_uuid_str, user_id_str) = (org_uuid.to_string(), user_id_val.to_string());

                        // Create comprehensive metadata
                        let response_metadata = serde_json::json!({
                            "request": {
                                "id": metadata.request_id,
                                "method": metadata.method,
                                "endpoint": metadata.endpoint,
                                "size_bytes": metadata.request_size,
                                "user_id": {
                                    "org_uuid": org_uuid_str,
                                    "user_id": user_id_str
                                },
                                "client_info": metadata.client_info
                            },
                            "response": {
                                "status": status.as_u16(),
                                "size_bytes": size,
                                "content_type": headers
                                    .get("content-type")
                                    .and_then(|h| h.to_str().ok())
                                    .unwrap_or("unknown")
                            },
                            "cache": {
                                //TODO collect cache data from req headers
                            },
                            "timing": {
                                "start_time": metadata.request_start,
                                "end_time": end,
                                "total_request_duration_ms": total_duration_ms,
                                "total_processing_time_us": total_duration_us,
                                "eden_processing_time_ms": total_duration_ms,
                                "eden_processing_time_us": total_duration_us,
                                "endpoint_processing_time_ms": endpoint_processing_time_ms,
                                "endpoint_processing_time_us": endpoint_processing_time_us,
                                "exclusive_duration_ms": exclusive_duration_ms,
                                "exclusive_duration_us": exclusive_duration_us,
                            },
                            "server": {
                                "hostname": std::env::var("HOSTNAME").unwrap_or_else(|_| "unknown".to_string()),
                                "version": std::env::var("APP_VERSION").unwrap_or_else(|_| "dev".to_string()),
                            }
                        });

                        let is_streaming = headers
                            .get("content-type")
                            .and_then(|value| value.to_str().ok())
                            .map(|value| value.starts_with("text/event-stream"))
                            .unwrap_or(false);

                        if is_streaming {
                            telemetry_data.write().await.mut_durations(|durations| durations.set_eden_response(end));

                            let response_length = body_size_or_content_length(&body, &headers);

                            let mut durations = telemetry_data.read().await.durations.clone();
                            let is_error = status.is_client_error() || status.is_server_error();
                            let labels_refs = labels_to_refs(&labels_clone);
                            let active_labels_refs = labels_to_refs(&active_labels_clone);
                            metrics_clone.eden.complete_request_with_active_labels(
                                response_length,
                                end,
                                &mut durations,
                                is_error,
                                &labels_refs,
                                &active_labels_refs,
                            );
                            telemetry_data.write().await.durations = durations;

                            let mut response_builder = HttpResponse::build(status);
                            for (name, value) in headers.iter() {
                                response_builder.insert_header((name.clone(), value.clone()));
                            }
                            insert_traceparent_header(&mut response_builder, &response_traceparent);
                            let http_response = response_builder.body(body);
                            let service_response = ServiceResponse::new(request, http_response).map_into_right_body();

                            return Ok(service_response);
                        }

                        let body_bytes = match actix_web::body::to_bytes(body).await {
                            Ok(bytes) => bytes,
                            Err(e) => return Err(actix_web::Error::from(e)),
                        };

                        // Try to parse existing JSON response and add metadata
                        let modified_response = match serde_json::from_slice::<Value>(&body_bytes) {
                            Ok(mut json_value) => {
                                // If it's a JSON object, add metadata field
                                if let Value::Object(ref mut map) = json_value {
                                    map.insert("_meta".to_string(), response_metadata);
                                } else {
                                    // If response isn't an object, wrap it
                                    json_value = serde_json::json!({
                                        "data": json_value,
                                        "_meta": response_metadata
                                    });
                                }
                                json_value
                            }
                            Err(_) => {
                                // Not JSON, create a new JSON wrapper
                                serde_json::json!({
                                    "data": String::from_utf8_lossy(&body_bytes),
                                    "_meta": response_metadata,
                                    "_note": "Original response was not JSON - converted to string"
                                })
                            }
                        };

                        let response_body = serde_json::to_vec_pretty(&modified_response).map_err(actix_web::Error::from)?;

                        let response_length = response_body.len() as u64;

                        // Preserve original content-type header for verbose mode too
                        let mut response_builder = HttpResponse::build(status);
                        if let Some(content_type) = headers.get("content-type") {
                            response_builder.insert_header(("content-type", content_type.clone()));
                        } else {
                            response_builder.content_type("application/json");
                        }
                        insert_traceparent_header(&mut response_builder, &response_traceparent);

                        let service_response = ServiceResponse::new(request, response_builder.body(response_body)).map_into_right_body();

                        let mut durations = telemetry_data.read().await.durations.clone();
                        let is_error = status.is_client_error() || status.is_server_error();
                        let labels_refs = labels_to_refs(&labels_clone);
                        let active_labels_refs = labels_to_refs(&active_labels_clone);
                        metrics_clone.eden.complete_request_with_active_labels(
                            response_length,
                            end,
                            &mut durations,
                            is_error,
                            &labels_refs,
                            &active_labels_refs,
                        );
                        telemetry_data.write().await.durations = durations;

                        Ok(service_response)
                    } else {
                        // Normal mode - Track response size
                        let response_length = body_size_or_content_length(&body, &headers);

                        let mut durations = {
                            let mut tw = telemetry_data.write().await;
                            tw.set_eden_request_end(end);
                            tw.mut_labels(|labels| {
                                labels.set_http_status(status);
                                // Note: trace IDs already set in async_block initialization
                            });
                            tw.durations.clone()
                        };

                        let is_error = status.is_client_error() || status.is_server_error();
                        let labels_refs = labels_to_refs(&labels_clone);
                        let active_labels_refs = labels_to_refs(&active_labels_clone);
                        metrics_clone.eden.complete_request_with_active_labels(
                            response_length,
                            end,
                            &mut durations,
                            is_error,
                            &labels_refs,
                            &active_labels_refs,
                        );
                        log_trace!(
                            _ctx.clone(),
                            "Metrics -- final durations",
                            audience = eden_logger_internal::LogAudience::Internal,
                            durations = format!("{:?}", durations)
                        );
                        telemetry_data.write().await.durations = durations;

                        // Reconstruct response while preserving all original headers
                        let mut response_builder = HttpResponse::build(status);
                        for (name, value) in headers.iter() {
                            response_builder.insert_header((name.clone(), value.clone()));
                        }
                        insert_traceparent_header(&mut response_builder, &response_traceparent);
                        let http_response = response_builder.body(body);
                        let service_response = ServiceResponse::new(request, http_response).map_into_right_body();

                        Ok(service_response)
                    }
                }
                Err(err) => {
                    log_trace!(_ctx, "Metrics -- service response error", audience = eden_logger_internal::LogAudience::Internal);
                    let endpoint_end = Utc::now();
                    let end = endpoint_end;

                    let (labels_clone, mut durations) = {
                        let mut tw = telemetry_data.write().await;
                        tw.set_eden_request_end(end);
                        tw.mut_labels(|labels| {
                            labels.set_http_status(StatusCode::INTERNAL_SERVER_ERROR);
                            // Note: trace IDs already set in async_block initialization
                        });

                        // Set endpoint duration if not already set
                        if tw.durations.get_endpoint_duration().is_none() {
                            tw.durations.set_endpoint_request(endpoint_start);
                            tw.durations.set_endpoint_response(endpoint_end);
                        }

                        (tw.labels_low_cardinality(), tw.durations.clone())
                    };

                    let labels_refs = labels_to_refs(&labels_clone);
                    let active_labels_refs = labels_to_refs(&active_labels_clone);
                    metrics_clone.eden.complete_request_with_active_labels(0, end, &mut durations, true, &labels_refs, &active_labels_refs);
                    telemetry_data.write().await.durations = durations;
                    // EndpointGuard will drop here, automatically recording all metrics even on error

                    Err(err)
                }
            }
        })
    }
}
