CREATE TABLE IF NOT EXISTS llm_gateway_api_keys (
    id UUID PRIMARY KEY,
    organization_uuid UUID NOT NULL REFERENCES organizations(uuid) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    key_prefix TEXT NOT NULL,
    endpoint_uuid UUID NOT NULL REFERENCES endpoints(uuid) ON DELETE CASCADE,
    agent_uuid UUID NOT NULL UNIQUE REFERENCES llm_agents(id) ON DELETE CASCADE,
    model_allowlist TEXT[],
    rate_limit_rpm BIGINT,
    budget_tokens_monthly BIGINT,
    pii_policy TEXT NOT NULL,
    custom_pii_terms JSONB NOT NULL DEFAULT '[]'::jsonb,
    price_arbitrage_mode TEXT NOT NULL,
    response_cache_ttl_secs BIGINT,
    route_optimization_mode TEXT NOT NULL,
    kv_cache_mode TEXT NOT NULL,
    kv_cache_ttl_secs BIGINT,
    route_switch_threshold_percent BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMP WITH TIME ZONE
);
