CREATE TABLE IF NOT EXISTS llm_agents (
    id UUID PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    description TEXT,
    prompt TEXT NOT NULL,
    cron_expression TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    scope JSONB NOT NULL DEFAULT '{"fresh": null}'::jsonb,
    overlap_policy TEXT NOT NULL DEFAULT 'skip',
    endpoint_uuid UUID NOT NULL,
    organization_uuid UUID NOT NULL,
    created_by UUID NOT NULL,
    robot_uuid UUID,
    skill_ids TEXT[] DEFAULT '{}',
    tool_endpoint_uuids TEXT[] DEFAULT '{}',
    orchestrate BOOLEAN NOT NULL DEFAULT true,
    max_consecutive_failures INTEGER NOT NULL DEFAULT 5,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    last_run_at TIMESTAMP WITH TIME ZONE,
    next_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
