mod analytics;
mod auth;
mod gateway;
mod keys;
mod snapshot_publisher;
mod state;

use crate::comm::endpoints::hydrate_llm_endpoint_config;
use actix_web::{HttpResponse, web};
use chrono::Utc;
use database::db::cache::CacheFunctions;
use database::db::lib::{ClickhouseConn, DatabaseManager, PgConn, RedisConn};
use eden_core::error::{ApiError, DatabaseError, EpError};
use eden_core::format::cache_id::EndpointCacheId;
use eden_core::format::cache_uuid::{CacheUuid, EndpointCacheUuid, OrganizationCacheUuid};
use eden_core::format::endpoint::EpKind;
use eden_core::format::{CacheObjectType, EdenUuid, EndpointId, EndpointUuid, OrganizationUuid};
use eden_core::telemetry::{FastSpan, FastSpanStatus, TelemetryWrapper};
use endpoint_core::endpoint::EndpointSchema;
use endpoint_core::llm_core::comm::LlmClient;
use endpoint_core::llm_core::connection::LlmConnection;
use endpoint_core::llm_core::{
    LlmConfig, LlmGovernancePolicy, LlmInvocation, LlmProviderMetadata, ResolvedLlmConnection, openai_error_envelope,
};
use std::borrow::Cow;
use std::sync::{Arc, RwLock};
use uuid::Uuid;

pub use gateway::{chat_completions, list_models, responses};
pub use keys::{
    ApiKey, ApiKeyResponse, CreateApiKeyRequest, CreateApiKeyResponse, OrgPiiDictionaryResponse, UpdateApiKeyRequest,
    UpdateOrgPiiDictionaryRequest, create_api_key, delete_api_key, gateway_control_plane_snapshot, get_org_pii_dictionary, list_api_keys,
    update_api_key, update_org_pii_dictionary,
};
// utoipa's `OpenApi` derive in `apidocs::api_docs_impl` resolves `paths(...)`
// entries against the module path where the handler reference lives, so the
// `__path_*` items generated by `#[utoipa::path]` in `keys.rs` need to be
// re-exported here for the snapshot derive to compile under `--features openapi`.
#[cfg(feature = "openapi")]
#[allow(non_camel_case_types, unused_imports)]
pub use keys::{
    __path_create_api_key, __path_delete_api_key, __path_get_org_pii_dictionary, __path_list_api_keys, __path_update_api_key,
    __path_update_org_pii_dictionary,
};
pub use snapshot_publisher::{GatewaySnapshotPublisherConfig, spawn_gateway_snapshot_publisher};
pub use state::{ProxyGatewayRuntimeSummary, ProxyGatewayState};

pub fn configure_routes(cfg: &mut web::ServiceConfig) {
    cfg.route("/chat/completions", web::post().to(chat_completions))
        .route("/responses", web::post().to(responses))
        .route("/models", web::get().to(list_models))
        .route("/gateway_snapshot", web::get().to(gateway_control_plane_snapshot))
        .route("/api_keys", web::get().to(list_api_keys))
        .route("/api_keys", web::post().to(create_api_key))
        .route("/api_keys/{key_id}", web::patch().to(update_api_key))
        .route("/api_keys/{key_id}", web::delete().to(delete_api_key))
        .route("/pii_dictionary", web::get().to(get_org_pii_dictionary))
        .route("/pii_dictionary", web::put().to(update_org_pii_dictionary));
}

pub(super) fn proxy_governance_policy(api_key: &ApiKey) -> LlmGovernancePolicy {
    let gateway_policy = api_key.gateway_policy();
    LlmGovernancePolicy {
        pii_action: gateway_policy.request_pii_action,
        model_allowlist: gateway_policy.model_allowlist,
        budget_tokens_monthly: gateway_policy.budget_tokens_monthly,
        rate_limit_rpm: gateway_policy.rate_limit_rpm,
    }
}

pub(super) fn parse_uuid_path(value: &str, field: &str) -> Result<Uuid, EpError> {
    Uuid::parse_str(value).map_err(|_| EpError::request(format!("{field} must be a valid UUID")))
}

pub async fn hydrate_gateway_api_keys(
    database: &DatabaseManager<RedisConn, PgConn, ClickhouseConn>,
    proxy_state: &ProxyGatewayState,
    telemetry_wrapper: &mut TelemetryWrapper,
) -> Result<usize, EpError> {
    let stored_keys = database.list_llm_gateway_api_keys(telemetry_wrapper).await?;
    let api_keys = stored_keys.into_iter().map(ApiKey::from).collect::<Vec<_>>();
    let hydrated_keys = proxy_state.hydrate_keys(api_keys.clone())?;

    let route_rollups = database.list_all_llm_gateway_route_rollups(50_000, telemetry_wrapper).await?;
    let hydrated_routes = proxy_state.hydrate_route_rollups(route_rollups.into_iter().map(|rollup| state::ProxyRouteRollupSeed {
        endpoint_uuid: rollup.endpoint_uuid,
        provider: rollup.provider,
        model: rollup.model,
        success_count: rollup.success_count,
        total_latency_ms: rollup.total_latency_ms,
        min_latency_ms: rollup.min_latency_ms,
        max_latency_ms: rollup.max_latency_ms,
        total_output_tokens: rollup.total_output_tokens,
        total_duration_ms: rollup.total_duration_ms,
        first_observed_at: rollup.first_observed_at,
        last_observed_at: rollup.last_observed_at,
    }));

    let org_dictionaries = database.list_org_pii_dictionaries(telemetry_wrapper).await?;
    let hydrated_org_dictionaries =
        proxy_state.hydrate_org_pii_dictionaries(org_dictionaries.into_iter().map(|entry| (entry.organization_uuid.uuid(), entry.terms)));

    let month_bucket = state::current_budget_month_bucket(Utc::now());
    let mut hydrated_budget_windows = 0_usize;
    for api_key in &api_keys {
        if api_key.budget_tokens_monthly.filter(|limit| *limit > 0).is_none() {
            continue;
        }
        if let Some(rollup) = database
            .get_llm_gateway_usage_rollup(
                &eden_core::format::OrganizationUuid::from(api_key.org_uuid),
                "api_key",
                &api_key.id.to_string(),
                month_bucket,
                telemetry_wrapper,
            )
            .await?
        {
            proxy_state.set_budget_usage(api_key.id, month_bucket, rollup.total_tokens);
            hydrated_budget_windows += 1;
        }
    }

    tracing::info!(
        route_rollup_count = hydrated_routes,
        budget_window_count = hydrated_budget_windows,
        org_pii_dictionary_count = hydrated_org_dictionaries,
        "Hydrated LLM gateway runtime state"
    );
    Ok(hydrated_keys)
}

pub(super) async fn fetch_llm_endpoint_schema(
    database: &DatabaseManager<RedisConn, PgConn, ClickhouseConn>,
    org_uuid: &OrganizationUuid,
    endpoint_uuid: EndpointUuid,
    telemetry_wrapper: &mut TelemetryWrapper,
) -> Result<EndpointSchema, EpError> {
    let organization_cache_uuid = OrganizationCacheUuid::new(None, org_uuid.clone());
    let cache_object =
        CacheObjectType::<EndpointCacheUuid, EndpointCacheId>::from((Some(organization_cache_uuid), endpoint_uuid.uuid().to_string()));

    let mut endpoint_schema = <DatabaseManager<RedisConn, PgConn, ClickhouseConn> as CacheFunctions<
        EndpointSchema,
        EndpointCacheUuid,
        EndpointUuid,
        EndpointCacheId,
        EndpointId,
    >>::get_from_cache(database, &cache_object, telemetry_wrapper)
    .await?;

    if endpoint_schema.kind() != EpKind::Llm {
        return Err(EpError::request("API keys can only target LLM endpoints"));
    }

    hydrate_llm_endpoint_config(database, &mut endpoint_schema, org_uuid, telemetry_wrapper).await?;
    Ok(endpoint_schema)
}

pub(super) fn build_proxy_client(endpoint_schema: &EndpointSchema) -> Result<(LlmClient, ResolvedLlmConnection, Option<String>), EpError> {
    let llm_config = endpoint_schema
        .config()
        .as_any()
        .downcast_ref::<LlmConfig>()
        .cloned()
        .ok_or_else(|| EpError::request("LLM config not found"))?;

    let credentials = llm_config
        .read_credentials
        .as_ref()
        .or(llm_config.write_credentials.as_ref())
        .ok_or_else(|| EpError::connect("LLM credentials missing"))?;
    let connection = LlmConnection::from_target_and_credentials(&llm_config.target, credentials);
    let credential_id = connection.credential_id.map(|id| id.to_string());
    let credential = connection.credential_id.and_then(|id| llm_config.credentials.get(&id));
    let resolved = connection.resolve(credential)?;
    let client = LlmClient::new(Arc::new(RwLock::new(resolved.clone())), llm_config.resolved_max_tool_passes())?;
    Ok((client, resolved, credential_id))
}

pub(super) fn provider_metadata_from_resolved(
    resolved: &ResolvedLlmConnection,
    invocation: &LlmInvocation,
) -> Result<LlmProviderMetadata, EpError> {
    let model = resolved.effective_model(invocation.overrides.model.clone());
    let base_url = resolved.base_url()?;
    Ok(LlmProviderMetadata::new(resolved.provider.to_string(), model, Some(base_url)))
}

pub(super) fn openai_error_response(status: actix_web::http::StatusCode, message: &str, error_type: &str, code: &str) -> HttpResponse {
    HttpResponse::build(status).json(openai_error_envelope(message, error_type, code))
}

pub(super) fn governance_block_error_response(message: &str) -> HttpResponse {
    if message.contains("model") {
        openai_error_response(actix_web::http::StatusCode::FORBIDDEN, message, "invalid_request_error", "model_not_allowed")
    } else {
        openai_error_response(actix_web::http::StatusCode::FORBIDDEN, message, "invalid_request_error", "pii_blocked")
    }
}

pub(super) fn openai_error_from_ep_error(error: EpError, span: &mut FastSpan) -> HttpResponse {
    let message = if error.should_expose_to_client() {
        error.to_string()
    } else {
        "request failed".to_string()
    };

    span.set_status(FastSpanStatus::Error { message: Cow::Owned(error.to_string()) });

    match error {
        EpError::Auth(_) => {
            openai_error_response(actix_web::http::StatusCode::UNAUTHORIZED, &message, "authentication_error", "invalid_api_key")
        }
        EpError::Rbac(_) => openai_error_response(actix_web::http::StatusCode::FORBIDDEN, &message, "invalid_request_error", "forbidden"),
        EpError::Database(DatabaseError::EndpointNotFound) => {
            openai_error_response(actix_web::http::StatusCode::NOT_FOUND, &message, "invalid_request_error", "endpoint_not_found")
        }
        EpError::Request(_)
        | EpError::Parse(_)
        | EpError::Serde(_)
        | EpError::Data(_)
        | EpError::Template(_)
        | EpError::Api(ApiError::InvalidRequest)
        | EpError::Api(ApiError::InvalidInput) => {
            openai_error_response(actix_web::http::StatusCode::BAD_REQUEST, &message, "invalid_request_error", "invalid_request")
        }
        EpError::Timeout(_) => openai_error_response(actix_web::http::StatusCode::GATEWAY_TIMEOUT, &message, "timeout_error", "timeout"),
        _ => openai_error_response(actix_web::http::StatusCode::BAD_GATEWAY, &message, "server_error", "upstream_error"),
    }
}
