INSERT INTO llm_gateway_response_cache (
    cache_key,
    organization_uuid,
    endpoint_uuid,
    key_id,
    provider,
    model,
    request_hash,
    prompt_fingerprint,
    response_json,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    estimated_cost_micros,
    created_at,
    updated_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
ON CONFLICT (cache_key) DO UPDATE
SET
    organization_uuid = EXCLUDED.organization_uuid,
    endpoint_uuid = EXCLUDED.endpoint_uuid,
    key_id = EXCLUDED.key_id,
    provider = EXCLUDED.provider,
    model = EXCLUDED.model,
    request_hash = EXCLUDED.request_hash,
    prompt_fingerprint = EXCLUDED.prompt_fingerprint,
    response_json = EXCLUDED.response_json,
    prompt_tokens = EXCLUDED.prompt_tokens,
    completion_tokens = EXCLUDED.completion_tokens,
    total_tokens = EXCLUDED.total_tokens,
    estimated_cost_micros = EXCLUDED.estimated_cost_micros,
    updated_at = EXCLUDED.updated_at,
    expires_at = EXCLUDED.expires_at
RETURNING
    cache_key,
    organization_uuid,
    endpoint_uuid,
    key_id,
    provider,
    model,
    request_hash,
    prompt_fingerprint,
    response_json,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    estimated_cost_micros,
    hit_count,
    created_at,
    updated_at,
    expires_at,
    last_hit_at;
