INSERT INTO llm_gateway_api_keys (
    id,
    organization_uuid,
    name,
    key_hash,
    key_prefix,
    endpoint_uuid,
    model_allowlist,
    rate_limit_rpm,
    budget_tokens_monthly,
    pii_policy,
    price_arbitrage_mode,
    response_cache_ttl_secs,
    route_optimization_mode,
    kv_cache_mode,
    kv_cache_ttl_secs,
    route_switch_threshold_percent,
    enabled,
    created_at,
    updated_at,
    last_used_at,
    agent_uuid,
    custom_pii_terms
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
ON CONFLICT (id) DO UPDATE
SET
    organization_uuid = EXCLUDED.organization_uuid,
    name = EXCLUDED.name,
    key_hash = EXCLUDED.key_hash,
    key_prefix = EXCLUDED.key_prefix,
    endpoint_uuid = EXCLUDED.endpoint_uuid,
    model_allowlist = EXCLUDED.model_allowlist,
    rate_limit_rpm = EXCLUDED.rate_limit_rpm,
    budget_tokens_monthly = EXCLUDED.budget_tokens_monthly,
    pii_policy = EXCLUDED.pii_policy,
    price_arbitrage_mode = EXCLUDED.price_arbitrage_mode,
    response_cache_ttl_secs = EXCLUDED.response_cache_ttl_secs,
    route_optimization_mode = EXCLUDED.route_optimization_mode,
    kv_cache_mode = EXCLUDED.kv_cache_mode,
    kv_cache_ttl_secs = EXCLUDED.kv_cache_ttl_secs,
    route_switch_threshold_percent = EXCLUDED.route_switch_threshold_percent,
    enabled = EXCLUDED.enabled,
    updated_at = EXCLUDED.updated_at,
    last_used_at = EXCLUDED.last_used_at,
    custom_pii_terms = EXCLUDED.custom_pii_terms
RETURNING
    id,
    organization_uuid,
    name,
    key_hash,
    key_prefix,
    endpoint_uuid,
    model_allowlist,
    rate_limit_rpm,
    budget_tokens_monthly,
    pii_policy,
    price_arbitrage_mode,
    response_cache_ttl_secs,
    route_optimization_mode,
    kv_cache_mode,
    kv_cache_ttl_secs,
    route_switch_threshold_percent,
    enabled,
    created_at,
    updated_at,
    last_used_at,
    agent_uuid,
    custom_pii_terms;
