INSERT INTO llm_gateway_route_rollups (
    organization_uuid,
    endpoint_uuid,
    provider,
    model,
    route_class,
    success_count,
    error_count,
    total_latency_ms,
    min_latency_ms,
    max_latency_ms,
    total_output_tokens,
    total_duration_ms,
    first_observed_at,
    last_observed_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (organization_uuid, endpoint_uuid, provider, model, route_class) DO UPDATE
SET
    success_count = EXCLUDED.success_count,
    error_count = EXCLUDED.error_count,
    total_latency_ms = EXCLUDED.total_latency_ms,
    min_latency_ms = EXCLUDED.min_latency_ms,
    max_latency_ms = EXCLUDED.max_latency_ms,
    total_output_tokens = EXCLUDED.total_output_tokens,
    total_duration_ms = EXCLUDED.total_duration_ms,
    first_observed_at = EXCLUDED.first_observed_at,
    last_observed_at = EXCLUDED.last_observed_at,
    updated_at = EXCLUDED.updated_at
RETURNING
    organization_uuid,
    endpoint_uuid,
    provider,
    model,
    route_class,
    success_count,
    error_count,
    total_latency_ms,
    min_latency_ms,
    max_latency_ms,
    total_output_tokens,
    total_duration_ms,
    first_observed_at,
    last_observed_at,
    updated_at;
