CREATE TABLE IF NOT EXISTS execution_runs (
    id TEXT PRIMARY KEY,
    organization_uuid TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    endpoint_uuid TEXT NOT NULL,
    trigger_kind TEXT NOT NULL,
    trigger_metadata TEXT NOT NULL DEFAULT '{}',
    conversation_id TEXT,
    agent_id TEXT,
    request_payload TEXT NOT NULL,
    state TEXT NOT NULL,
    plan TEXT,
    checkpoint TEXT,
    response_text TEXT,
    error TEXT,
    duration_ms INTEGER,
    idempotency_key TEXT,
    total_tokens INTEGER,
    total_cost_usd REAL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    completed_at TEXT
);
