CREATE TABLE IF NOT EXISTS llm_gateway_response_cache (
    cache_key TEXT PRIMARY KEY,
    organization_uuid TEXT NOT NULL REFERENCES organizations(uuid) ON DELETE CASCADE,
    endpoint_uuid TEXT NOT NULL REFERENCES endpoints(uuid) ON DELETE CASCADE,
    key_id TEXT NOT NULL REFERENCES llm_gateway_api_keys(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    prompt_fingerprint TEXT,
    response_json TEXT NOT NULL,
    prompt_tokens INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    estimated_cost_micros INTEGER NOT NULL DEFAULT 0,
    hit_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    last_hit_at TEXT
);
