CREATE TABLE IF NOT EXISTS llm_agents (
    id TEXT PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    description TEXT,
    prompt TEXT NOT NULL,
    cron_expression TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    scope TEXT NOT NULL DEFAULT '{"fresh": null}',
    overlap_policy TEXT NOT NULL DEFAULT 'skip',
    endpoint_uuid TEXT NOT NULL,
    organization_uuid TEXT NOT NULL,
    created_by TEXT NOT NULL,
    robot_uuid TEXT,
    skill_ids TEXT DEFAULT '[]',
    tool_endpoint_uuids TEXT DEFAULT '[]',
    orchestrate INTEGER NOT NULL DEFAULT 1,
    max_consecutive_failures INTEGER NOT NULL DEFAULT 5,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    last_run_at TEXT,
    next_run_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
